name = "PROPHECY"
author = "W.D. GASTER @ ROYAL SCIENCES INC"
version = "1.0.0"
description = "MY. DELTARUNE."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0d21a789ac1d9d440b1f7a9687b7033ba1030efc09886c148aa55fd3238b18c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
