name = "PROPHECY"
author = "W.D. GASTER @ ROYAL SCIENCES INC"
version = "1.0.0"
description = "MY. DELTARUNE."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f45ab4fd890bbcdf89696446b7db1a51448c0070e59738ef945ff0bf7e81d3bc"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
