name = "PROPHECY"
author = "W.D. GASTER @ ROYAL SCIENCES INC"
version = "1.0.0"
description = "MY. DELTARUNE."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42d846cf2bf520efdb41d881a4f4c071b1e968f079f4d6926ab2b8688e8a8db5"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
